version: '3'

services: 
  redis:
    image: redis
    ports: 
      - "6379:6379"
    volumes: 
      - "redisdata:/data"
  app:
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - "redis"
volumes: 
  redisdata :  