- hosts: "{{ HOSTS }}"
  become: yes
  tasks:
    - name : "check document root directory"
      command: ls /opt/htdocs
      register: documentroot
      ignore_errors: true


    - name : "show variable"
      debug:
        var: documentroot
        
    - name : "Create document root directory"
      command: mkdir /opt/htdocs
      when: documentroot.rc != 0
